export const typography = {
  fontFamily: {
    regular: 'Inter-Regular',
    medium: 'Inter-Medium',
    semibold: 'Inter-SemiBold',
    bold: 'Inter-Bold',
  },
  fontSize: {
    caption: 12,
    label: 12,
    bodySmall: 14,
    body: 16,
    button: 16,
    subtitle: 18,
    title: 22,
    headline: 28,
    display: 32,
  },
  lineHeight: {
    caption: 16,
    label: 16,
    bodySmall: 20,
    body: 24,
    button: 24,
    subtitle: 24,
    title: 28,
    headline: 36,
    display: 40,
  },
  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
  letterSpacing: {
    caption: 0,
    label: 0.5,
    bodySmall: 0,
    body: 0,
    button: 0,
    subtitle: 0,
    title: -0.2,
    headline: -0.3,
    display: -0.5,
  },
} as const;

export const textStyles = {
  display: {
    fontSize: typography.fontSize.display,
    lineHeight: typography.lineHeight.display,
    fontWeight: typography.fontWeight.bold,
    fontFamily: typography.fontFamily.bold,
    letterSpacing: typography.letterSpacing.display,
  },
  headline: {
    fontSize: typography.fontSize.headline,
    lineHeight: typography.lineHeight.headline,
    fontWeight: typography.fontWeight.bold,
    fontFamily: typography.fontFamily.bold,
    letterSpacing: typography.letterSpacing.headline,
  },
  title: {
    fontSize: typography.fontSize.title,
    lineHeight: typography.lineHeight.title,
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.semibold,
    letterSpacing: typography.letterSpacing.title,
  },
  subtitle: {
    fontSize: typography.fontSize.subtitle,
    lineHeight: typography.lineHeight.subtitle,
    fontWeight: typography.fontWeight.medium,
    fontFamily: typography.fontFamily.medium,
    letterSpacing: typography.letterSpacing.subtitle,
  },
  body: {
    fontSize: typography.fontSize.body,
    lineHeight: typography.lineHeight.body,
    fontWeight: typography.fontWeight.regular,
    fontFamily: typography.fontFamily.regular,
    letterSpacing: typography.letterSpacing.body,
  },
  bodySmall: {
    fontSize: typography.fontSize.bodySmall,
    lineHeight: typography.lineHeight.bodySmall,
    fontWeight: typography.fontWeight.regular,
    fontFamily: typography.fontFamily.regular,
    letterSpacing: typography.letterSpacing.bodySmall,
  },
  caption: {
    fontSize: typography.fontSize.caption,
    lineHeight: typography.lineHeight.caption,
    fontWeight: typography.fontWeight.medium,
    fontFamily: typography.fontFamily.medium,
    letterSpacing: typography.letterSpacing.caption,
  },
  label: {
    fontSize: typography.fontSize.label,
    lineHeight: typography.lineHeight.label,
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.semibold,
    letterSpacing: typography.letterSpacing.label,
    textTransform: 'uppercase' as const,
  },
  button: {
    fontSize: typography.fontSize.button,
    lineHeight: typography.lineHeight.button,
    fontWeight: typography.fontWeight.semibold,
    fontFamily: typography.fontFamily.semibold,
    letterSpacing: typography.letterSpacing.button,
  },
} as const;

export type TextStyleName = keyof typeof textStyles;
