import { supabase } from '../../infrastructure/database';
import {
  AuthRemoteDataSource,
  ReportRemoteDataSource,
  EventRemoteDataSource,
  RecyclingCenterRemoteDataSource,
  CommunityRemoteDataSource,
  AdminRemoteDataSource,
} from '../../data/datasources/remote';
import { OperatorDatasource } from '../../data/datasources/operator.datasource';
import {
  AuthRepositoryImpl,
  ReportRepositoryImpl,
  EventRepositoryImpl,
  RecyclingCenterRepositoryImpl,
  CommunityRepository,
  PostRepository,
  PollRepository,
  OperatorRepositoryImpl,
  AdminRepositoryImpl,
} from '../../data/repositories';
import {
  SignInUseCase,
  SignUpUseCase,
  CitizenSignUpUseCase,
  SignOutUseCase,
  GetCurrentUserUseCase,
  ResetPasswordUseCase,
  UpdatePasswordUseCase,
  ResendVerificationUseCase,
  GetReportsUseCase,
  GetReportByIdUseCase,
  GetMyReportsUseCase,
  CreateReportUseCase,
  UpdateReportStatusUseCase,
  GetReportCommentsUseCase,
  AddReportCommentUseCase,
  GetReportTimelineUseCase,
  GetEventsUseCase,
  GetEventByIdUseCase,
  GetUpcomingEventsUseCase,
  GetNearbyEventsUseCase,
  GetPopularEventsUseCase,
  GetCommunityEventsUseCase,
  GetMyEventsUseCase,
  CreateEventUseCase,
  UpdateEventUseCase,
  CancelEventUseCase,
  JoinEventUseCase,
  LeaveEventUseCase,
  GetEventParticipantsUseCase,
  IsRegisteredUseCase,
  ToggleFavoriteUseCase,
  GetFavoritesUseCase,
  IsFavoriteUseCase,
  MarkAttendanceUseCase,
  GetAttendanceUseCase,
  SetReminderUseCase,
  GetRemindersUseCase,
  GetRecyclingCentersUseCase,
  GetRecyclingCenterByIdUseCase,
  GetNearbyCentersUseCase,
  SearchCentersUseCase,
  GetCenterReviewsUseCase,
  AddCenterReviewUseCase,
  DeleteCenterReviewUseCase,
  MarkReviewHelpfulUseCase,
  GetCenterRatingUseCase,
  SetCenterRatingUseCase,
  ToggleCenterFavoriteUseCase,
  GetCenterFavoritesUseCase,
  IsCenterFavoriteUseCase,
  GetCommunitiesUseCase,
  GetCommunityUseCase,
  CreateCommunityUseCase,
  UpdateCommunityUseCase,
  DeleteCommunityUseCase,
  JoinCommunityUseCase,
  LeaveCommunityUseCase,
  GetCommunityMembersUseCase,
  UpdateMemberRoleUseCase,
  GetJoinedCommunitiesUseCase,
  IsMemberUseCase,
  GetPostsUseCase,
  GetPostUseCase,
  CreatePostUseCase,
  UpdatePostUseCase,
  DeletePostUseCase,
  PinPostUseCase,
  GetCommentsUseCase,
  CreateCommentUseCase,
  DeleteCommentUseCase,
  AddReactionUseCase,
  RemoveReactionUseCase,
  BookmarkPostUseCase,
  RemoveBookmarkUseCase,
  GetBookmarkedPostsUseCase,
  IsBookmarkedUseCase,
  GetPollUseCase,
  CreatePollUseCase,
  UpdatePollUseCase,
  DeletePollUseCase,
  AddPollOptionUseCase,
  RemovePollOptionUseCase,
  VotePollUseCase,
  RemoveVoteUseCase,
  HasVotedUseCase,
  GetAssignedReportsUseCase,
  GetPendingReportsUseCase,
  GetReportDetailsUseCase,
  AssignReportUseCase,
  UnassignReportUseCase,
  ResolveReportUseCase,
  RejectReportUseCase,
  LogOperatorActivityUseCase,
  GetOperatorActivityUseCase,
  GetOperatorStatsUseCase,
  GetOperatorPerformanceUseCase,
  GetTodayRouteUseCase,
  OptimizeRouteUseCase,
  GetDashboardStatsUseCase,
  GetActivityDataUseCase,
  GetReportsByCategoryUseCase,
  GetReportsByDistrictUseCase,
  GetActivityLogsUseCase,
  LogActivityUseCase,
  GetSettingsUseCase,
  UpdateSettingUseCase,
  GetAnalyticsUseCase,
  ExportAnalyticsUseCase,
  GetUsersUseCase,
  GetUserByIdUseCase,
  UpdateUserUseCase,
  ActivateUserUseCase,
  DeactivateUserUseCase,
  SuspendUserUseCase,
  RestoreUserUseCase,
  DeleteUserUseCase,
  AssignRoleUseCase,
  AdminResetPasswordUseCase,
  GetUserStatisticsUseCase,
  AdminGetReportsUseCase,
  AdminGetReportByIdUseCase,
  AdminAssignReportUseCase,
  AdminUpdateReportStatusUseCase,
  AdminUpdateReportPriorityUseCase,
} from '../../domain/use-cases';

const authDataSource = new AuthRemoteDataSource(supabase);
const reportDataSource = new ReportRemoteDataSource(supabase);
const eventDataSource = new EventRemoteDataSource(supabase);
const recyclingCenterDataSource = new RecyclingCenterRemoteDataSource(supabase);
const communityDataSource = new CommunityRemoteDataSource(supabase);
const operatorDataSource = new OperatorDatasource();

const authRepository = new AuthRepositoryImpl(authDataSource);
const reportRepository = new ReportRepositoryImpl(reportDataSource);
const eventRepository = new EventRepositoryImpl(eventDataSource);
const recyclingCenterRepository = new RecyclingCenterRepositoryImpl(recyclingCenterDataSource);
const communityRepository = new CommunityRepository(communityDataSource);
const postRepository = new PostRepository(communityDataSource);
const pollRepository = new PollRepository(communityDataSource);
const operatorRepository = new OperatorRepositoryImpl(operatorDataSource);

const adminDataSource = new AdminRemoteDataSource(supabase);
const adminRepository = new AdminRepositoryImpl(adminDataSource);

export const container = {
  authUseCases: {
    signIn: new SignInUseCase(authRepository),
    signUp: new SignUpUseCase(authRepository),
    signUpCitizen: new CitizenSignUpUseCase(authRepository),
    signOut: new SignOutUseCase(authRepository),
    getCurrentUser: new GetCurrentUserUseCase(authRepository),
    resetPassword: new ResetPasswordUseCase(authRepository),
    updatePassword: new UpdatePasswordUseCase(authRepository),
    resendVerification: new ResendVerificationUseCase(authRepository),
  },
  reportUseCases: {
    getReports: new GetReportsUseCase(reportRepository),
    getReportById: new GetReportByIdUseCase(reportRepository),
    getMyReports: new GetMyReportsUseCase(reportRepository),
    createReport: new CreateReportUseCase(reportRepository),
    updateReportStatus: new UpdateReportStatusUseCase(reportRepository),
    getReportComments: new GetReportCommentsUseCase(reportRepository),
    addReportComment: new AddReportCommentUseCase(reportRepository),
    getReportTimeline: new GetReportTimelineUseCase(reportRepository),
  },
  eventUseCases: {
    getEvents: new GetEventsUseCase(eventRepository),
    getEventById: new GetEventByIdUseCase(eventRepository),
    getUpcoming: new GetUpcomingEventsUseCase(eventRepository),
    getNearby: new GetNearbyEventsUseCase(eventRepository),
    getPopular: new GetPopularEventsUseCase(eventRepository),
    getCommunityEvents: new GetCommunityEventsUseCase(eventRepository),
    getMyEvents: new GetMyEventsUseCase(eventRepository),
    createEvent: new CreateEventUseCase(eventRepository),
    updateEvent: new UpdateEventUseCase(eventRepository),
    cancelEvent: new CancelEventUseCase(eventRepository),
    joinEvent: new JoinEventUseCase(eventRepository),
    leaveEvent: new LeaveEventUseCase(eventRepository),
    getParticipants: new GetEventParticipantsUseCase(eventRepository),
    isRegistered: new IsRegisteredUseCase(eventRepository),
    toggleFavorite: new ToggleFavoriteUseCase(eventRepository),
    getFavorites: new GetFavoritesUseCase(eventRepository),
    isFavorite: new IsFavoriteUseCase(eventRepository),
    markAttendance: new MarkAttendanceUseCase(eventRepository),
    getAttendance: new GetAttendanceUseCase(eventRepository),
    setReminder: new SetReminderUseCase(eventRepository),
    getReminders: new GetRemindersUseCase(eventRepository),
  },
  recyclingCenterUseCases: {
    getAll: new GetRecyclingCentersUseCase(recyclingCenterRepository),
    getById: new GetRecyclingCenterByIdUseCase(recyclingCenterRepository),
    getNearby: new GetNearbyCentersUseCase(recyclingCenterRepository),
    search: new SearchCentersUseCase(recyclingCenterRepository),
    getReviews: new GetCenterReviewsUseCase(recyclingCenterRepository),
    addReview: new AddCenterReviewUseCase(recyclingCenterRepository),
    deleteReview: new DeleteCenterReviewUseCase(recyclingCenterRepository),
    markReviewHelpful: new MarkReviewHelpfulUseCase(recyclingCenterRepository),
    getRating: new GetCenterRatingUseCase(recyclingCenterRepository),
    setRating: new SetCenterRatingUseCase(recyclingCenterRepository),
    toggleFavorite: new ToggleCenterFavoriteUseCase(recyclingCenterRepository),
    getFavorites: new GetCenterFavoritesUseCase(recyclingCenterRepository),
    isFavorite: new IsCenterFavoriteUseCase(recyclingCenterRepository),
  },
  communityUseCases: {
    getCommunities: new GetCommunitiesUseCase(communityRepository),
    getCommunity: new GetCommunityUseCase(communityRepository),
    createCommunity: new CreateCommunityUseCase(communityRepository),
    updateCommunity: new UpdateCommunityUseCase(communityRepository),
    deleteCommunity: new DeleteCommunityUseCase(communityRepository),
    joinCommunity: new JoinCommunityUseCase(communityRepository),
    leaveCommunity: new LeaveCommunityUseCase(communityRepository),
    getMembers: new GetCommunityMembersUseCase(communityRepository),
    updateMemberRole: new UpdateMemberRoleUseCase(communityRepository),
    getJoinedCommunities: new GetJoinedCommunitiesUseCase(communityRepository),
    isMember: new IsMemberUseCase(communityRepository),
  },
  postUseCases: {
    getPosts: new GetPostsUseCase(postRepository),
    getPost: new GetPostUseCase(postRepository),
    createPost: new CreatePostUseCase(postRepository),
    updatePost: new UpdatePostUseCase(postRepository),
    deletePost: new DeletePostUseCase(postRepository),
    pinPost: new PinPostUseCase(postRepository),
    getComments: new GetCommentsUseCase(postRepository),
    createComment: new CreateCommentUseCase(postRepository),
    deleteComment: new DeleteCommentUseCase(postRepository),
    addReaction: new AddReactionUseCase(postRepository),
    removeReaction: new RemoveReactionUseCase(postRepository),
    bookmarkPost: new BookmarkPostUseCase(postRepository),
    removeBookmark: new RemoveBookmarkUseCase(postRepository),
    getBookmarkedPosts: new GetBookmarkedPostsUseCase(postRepository),
    isBookmarked: new IsBookmarkedUseCase(postRepository),
  },
  pollUseCases: {
    getPoll: new GetPollUseCase(pollRepository),
    createPoll: new CreatePollUseCase(pollRepository),
    updatePoll: new UpdatePollUseCase(pollRepository),
    deletePoll: new DeletePollUseCase(pollRepository),
    addPollOption: new AddPollOptionUseCase(pollRepository),
    removePollOption: new RemovePollOptionUseCase(pollRepository),
    votePoll: new VotePollUseCase(pollRepository),
    removeVote: new RemoveVoteUseCase(pollRepository),
    hasVoted: new HasVotedUseCase(pollRepository),
  },
  operatorUseCases: {
    getAssignedReports: new GetAssignedReportsUseCase(operatorRepository),
    getPendingReports: new GetPendingReportsUseCase(operatorRepository),
    getReportDetails: new GetReportDetailsUseCase(operatorRepository),
    assignReport: new AssignReportUseCase(operatorRepository),
    unassignReport: new UnassignReportUseCase(operatorRepository),
    updateReportStatus: new UpdateReportStatusUseCase(operatorRepository),
    resolveReport: new ResolveReportUseCase(operatorRepository),
    rejectReport: new RejectReportUseCase(operatorRepository),
    logActivity: new LogOperatorActivityUseCase(operatorRepository),
    getActivity: new GetOperatorActivityUseCase(operatorRepository),
    getStats: new GetOperatorStatsUseCase(operatorRepository),
    getPerformance: new GetOperatorPerformanceUseCase(operatorRepository),
    getTodayRoute: new GetTodayRouteUseCase(operatorRepository),
    optimizeRoute: new OptimizeRouteUseCase(operatorRepository),
  },
  adminUseCases: {
    getDashboardStats: new GetDashboardStatsUseCase(adminRepository),
    getActivityData: new GetActivityDataUseCase(adminRepository),
    getReportsByCategory: new GetReportsByCategoryUseCase(adminRepository),
    getReportsByDistrict: new GetReportsByDistrictUseCase(adminRepository),
    getActivityLogs: new GetActivityLogsUseCase(adminRepository),
    logActivity: new LogActivityUseCase(adminRepository),
    getSettings: new GetSettingsUseCase(adminRepository),
    updateSetting: new UpdateSettingUseCase(adminRepository),
    getAnalytics: new GetAnalyticsUseCase(adminRepository),
    exportAnalytics: new ExportAnalyticsUseCase(adminRepository),
    getUsers: new GetUsersUseCase(adminRepository),
    getUserById: new GetUserByIdUseCase(adminRepository),
    updateUser: new UpdateUserUseCase(adminRepository),
    activateUser: new ActivateUserUseCase(adminRepository),
    deactivateUser: new DeactivateUserUseCase(adminRepository),
    suspendUser: new SuspendUserUseCase(adminRepository),
    restoreUser: new RestoreUserUseCase(adminRepository),
    deleteUser: new DeleteUserUseCase(adminRepository),
    assignRole: new AssignRoleUseCase(adminRepository),
    resetPassword: new AdminResetPasswordUseCase(adminRepository),
    getUserStatistics: new GetUserStatisticsUseCase(adminRepository),
    getReports: new AdminGetReportsUseCase(adminRepository),
    getReportById: new AdminGetReportByIdUseCase(adminRepository),
    assignReport: new AdminAssignReportUseCase(adminRepository),
    updateReportStatus: new AdminUpdateReportStatusUseCase(adminRepository),
    updateReportPriority: new AdminUpdateReportPriorityUseCase(adminRepository),
  },
} as const;
