export interface ThemeColors {
  primary: string;
  primaryLight: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  secondaryLight: string;
  onSecondary: string;
  background: string;
  surface: string;
  surfaceVariant: string;
  onSurface: string;
  onSurfaceVariant: string;
  border: string;
  divider: string;
  textPrimary: string;
  textSecondary: string;
  textDisabled: string;
  success: string;
  successLight: string;
  warning: string;
  warningLight: string;
  error: string;
  errorLight: string;
  errorContainer: string;
  onErrorContainer: string;
  info: string;
  infoLight: string;
}

export const citizenThemeColors: ThemeColors = {
  primary: '#10B981',
  primaryLight: '#D1FAE5',
  onPrimary: '#FFFFFF',
  primaryContainer: '#D1FAE5',
  onPrimaryContainer: '#065F46',
  secondary: '#059669',
  secondaryLight: '#A7F3D0',
  onSecondary: '#FFFFFF',
  background: '#F8FAFC',
  surface: '#FFFFFF',
  surfaceVariant: '#F1F5F9',
  onSurface: '#0F172A',
  onSurfaceVariant: '#64748B',
  border: '#E2E8F0',
  divider: '#E2E8F0',
  textPrimary: '#0F172A',
  textSecondary: '#64748B',
  textDisabled: '#94A3B8',
  success: '#22C55E',
  successLight: '#DCFCE7',
  warning: '#F59E0B',
  warningLight: '#FEF3C7',
  error: '#EF4444',
  errorLight: '#FEE2E2',
  errorContainer: '#FEE2E2',
  onErrorContainer: '#991B1B',
  info: '#3B82F6',
  infoLight: '#DBEAFE',
};

export const operatorThemeColors: ThemeColors = {
  primary: '#2563EB',
  primaryLight: '#DBEAFE',
  onPrimary: '#FFFFFF',
  primaryContainer: '#DBEAFE',
  onPrimaryContainer: '#1E40AF',
  secondary: '#1D4ED8',
  secondaryLight: '#BFDBFE',
  onSecondary: '#FFFFFF',
  background: '#F8FAFC',
  surface: '#FFFFFF',
  surfaceVariant: '#F1F5F9',
  onSurface: '#0F172A',
  onSurfaceVariant: '#64748B',
  border: '#E2E8F0',
  divider: '#E2E8F0',
  textPrimary: '#0F172A',
  textSecondary: '#64748B',
  textDisabled: '#94A3B8',
  success: '#22C55E',
  successLight: '#DCFCE7',
  warning: '#F59E0B',
  warningLight: '#FEF3C7',
  error: '#EF4444',
  errorLight: '#FEE2E2',
  errorContainer: '#FEE2E2',
  onErrorContainer: '#991B1B',
  info: '#3B82F6',
  infoLight: '#DBEAFE',
};

export const adminThemeColors: ThemeColors = {
  primary: '#059669',
  primaryLight: '#D1FAE5',
  onPrimary: '#FFFFFF',
  primaryContainer: '#D1FAE5',
  onPrimaryContainer: '#065F46',
  secondary: '#2563EB',
  secondaryLight: '#DBEAFE',
  onSecondary: '#FFFFFF',
  background: '#F8FAFC',
  surface: '#FFFFFF',
  surfaceVariant: '#F1F5F9',
  onSurface: '#0F172A',
  onSurfaceVariant: '#64748B',
  border: '#E2E8F0',
  divider: '#E2E8F0',
  textPrimary: '#0F172A',
  textSecondary: '#64748B',
  textDisabled: '#94A3B8',
  success: '#22C55E',
  successLight: '#DCFCE7',
  warning: '#F59E0B',
  warningLight: '#FEF3C7',
  error: '#EF4444',
  errorLight: '#FEE2E2',
  errorContainer: '#FEE2E2',
  onErrorContainer: '#991B1B',
  info: '#3B82F6',
  infoLight: '#DBEAFE',
};
